routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontoffice.index');
// });

// Frontoffice
Route::controller(App\Http\Controllers\Frontoffice\DashboardController::class)->group(function() {
    Route::get('/', 'index')->name('index');
    Route::get('/get_education', 'get_education')->name('get.education');
    Route::get('/get_education/{id}', 'get_show_education')->name('get.education.show');
    Route::get('/get_skill', 'get_skill')->name('get.skill');
    Route::get('/get_experience', 'get_experience')->name('get.experience');
    Route::get('/get_experience/{id}', 'get_show_experience')->name('get.experience.show');
    Route::get('/get_portfolio', 'get_portfolio')->name('get.portfolio');
    Route::get('/get_portfolio/{id}', 'get_show_portfolio')->name('get.portfolio.show');

    Route::post('/post_message', 'post_message')->name('post.message');
});


// Backoffice
Route::controller(App\Http\Controllers\Backoffice\AuthController::class)->group(function () {
    Route::view("backoffice/login", 'backoffice.auth.login')->name("login");
    Route::post("backoffice/login", 'login')->name('post_login');

    Route::get("backoffice/logout", 'logout')->name('logout');
});

Route::group(['middleware' => ['auth', 'auth.session']], function () {
    Route::prefix('backoffice')->name('backoffice.')->group(function() {
        Route::view('/', 'backoffice.dashboard.index')->name('raw_index');
        Route::view('/index', 'backoffice.dashboard.index')->name('index');

        Route::resources([
            'information' => App\Http\Controllers\Backoffice\InformationController::class,
            'education' => App\Http\Controllers\Backoffice\EducationController::class,
            'experience' => App\Http\Controllers\Backoffice\ExperienceController::class,
            'project' => App\Http\Controllers\Backoffice\ProjectController::class,
            'skill' => App\Http\Controllers\Backoffice\SkillController::class,
        ]);
    });
});

app/Http/Controllers/Backoffice/AuthController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Backoffice\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AuthController extends Controller
{
    public function login(Request $request)
    {
        try {
            $validated = Validator::make($request->all(), [
                'email' => 'required',
                'password' => 'required'
            ]);
    
            if ($validated->fails()) {
                $this->response_body['message'] = $validated->errors()->all();
                return $this->_generate_response(422);
            }

            if (Auth::guard('web')->attempt([
                'email' => $request->email,
                'password' => $request->password
            ])) {
                Auth::guard('web')->logoutOtherDevices($request->password);
                $request->session()->regenerate();
                $this->response_body['status'] = "True";
                $this->response_body['message'] = "Login Success";
                $this->response_body['data'] = route('backoffice.index');
                $status = 200;
    
            } else {
                $this->response_body['message'] = "Email or Password Mismatch";
                $status = 500;
            }
        } catch (\Throwable $t) {
            $this->response_body['message'] = $t->getMessage();
            $status = 500;
        }

        return $this->_generate_response($status);
    }

    public function logout()
    {
        Auth::guard('web')->logout();

        return redirect(route('login'));
    }
}

app/Http/Controllers/Backoffice/Controller.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Controller as BaseController;
use Illuminate\Http\Request;

class Controller extends BaseController
{
    protected $response_body = [
        'status' => False,
        'message' => '',
        'data' => ''
    ];

    protected $template = "";
    protected $template_data = [];

    public function _generate_response($response_code)
    {
        return response()->json($this->response_body, $response_code);
    }

    public function index()
    {
        return view("{$this->template}.index", $this->template_data);
    }

    public function create()
    {
        return view("{$this->template}.create", $this->template_data);
    }
}

app/Http/Controllers/Backoffice/DashboardController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    //
}

app/Http/Controllers/Backoffice/EducationController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Backoffice\Controller;
use App\Models\Education;
use Illuminate\Http\Request;

class EducationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->template = "backoffice.education";
        $this->template_data = [
            'title' => "Backoffice > Pendidikan",
        ];
    }

    public function index()
    {
        $this->template_data['data'] = Education::all();

        return parent::index();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $status = 200;
            $raw_desc = html_entity_decode($request->description);
            $desc = $raw_desc;

            if (strlen($raw_desc) > 155) {
                $desc = substr($raw_desc, 0, 155);
            }

            $created = array_merge($request->all(), [
                'short_description' => $desc,
                'start' => "{$request->start}-01",
                'end' => "{$request->end}-01",
            ]);

            Education::create($created);

            $this->response_body['status'] = True;
            $this->response_body['message'] = "Education is saved";
            $this->response_body['data'] = route('backoffice.education.index');
        } catch (\Throwable $t) {
            $this->response_body['status'] = False;
            $this->response_body['message'] = $t->getMessage();
            $status = 500;
        }

        return $this->_generate_response($status);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function show(Education $education)
    {
        try {
            $status = 200;

            $this->response_body['status'] = True;
            $this->response_body['data'] = $education;
        } catch (\Throwable $t) {
            $this->response_body['status'] = False;
            $this->response_body['message'] = $t->getMessage();
            $status = 500;
        }

        return $this->_generate_response($status);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function edit(Education $education)
    {
        $this->template_data['education'] = $education;
        return view("{$this->template}.edit", $this->template_data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Education $education)
    {
        try {
            $status = 200;
            $raw_desc = html_entity_decode($request->description);
            $desc = $raw_desc;

            if (strlen($raw_desc) > 155) {
                $desc = substr($raw_desc, 0, 155);
            }

            $update = array_merge($request->all(), [
                'short_description' => $desc,
                'start' => "{$request->start}-01",
                'end' => "{$request->end}-01",
            ]);

            $education->update($update);

            $this->response_body['status'] = True;
            $this->response_body['message'] = "Education is updated";
            $this->response_body['data'] = route('backoffice.education.index');
        } catch (\Throwable $t) {
            $this->response_body['status'] = False;
            $this->response_body['message'] = $t->getMessage();
            $status = 500;
        }

        return $this->_generate_response($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Education  $education
     * @return \Illuminate\Http\Response
     */
    public function destroy(Education $education)
    {
        //
    }
}

app/Http/Controllers/Backoffice/ExperienceController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Backoffice\Controller;
use App\Models\Experience;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ExperienceController extends Controller
{
    public function __construct()
    {
        $this->template = "backoffice.experience";
        $this->template_data = [
            'title' => "Backoffice > Pengalaman Bekerja",
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->template_data['data'] = Experience::all();

        return parent::index();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $status = 200;
            $raw_desc = html_entity_decode($request->description);
            $desc = $raw_desc;
            $val = "";

            if (strlen($raw_desc) > 155) {
                $desc = substr($raw_desc, 0, 155);
            }

            do {
                $val = substr(str_shuffle(str_repeat("0123456789abcdefghijklmnopqrstuvwxyz", 5)), 0, 5);
                $val = "{$val}.{$request->file('logo')->extension()}";
            } while (!empty(Experience::where('logo_company', $val)->first()));

            Storage::disk('public')->putFileAs(
                "experience",
                $request->file('logo'),
                $val
            );

            $created = array_merge($request->except('logo'), [
                'short_description' => $desc,
                'start' => "{$request->start}-01",
                'end' => empty($request->end) ? null : "{$request->end}-01",
                'logo_company' => $val,
            ]);

            Experience::create($created);

            $this->response_body['status'] = True;
            $this->response_body['message'] = "Experience is saved";
            $this->response_body['data'] = route('backoffice.experience.index');
        } catch (\Throwable $t) {
            $this->response_body['status'] = False;
            $this->response_body['message'] = $t->getMessage();
            $status = 500;
        }

        return $this->_generate_response($status);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function show(Experience $experience)
    {
        try {
            $status = 200;

            $this->response_body['status'] = True;
            $this->response_body['data'] = $experience;
        } catch (\Throwable $t) {
            $this->response_body['status'] = False;
            $this->response_body['message'] = $t->getMessage();
            $status = 500;
        }

        return $this->_generate_response($status);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function edit(Experience $experience)
    {
        $this->template_data['experience'] = $experience;
        return view("{$this->template}.edit", $this->template_data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Experience $experience)
    {
        try {
            $status = 200;
            $raw_desc = html_entity_decode($request->description);
            $desc = $raw_desc;
            $val = "";

            if (strlen($raw_desc) > 155) {
                $desc = substr($raw_desc, 0, 155);
            }

            $updated = array_merge($request->except('logo'), [
                'short_description' => $desc,
                'start' => "{$request->start}-01",
                'end' => empty($request->end) ? null : "{$request->end}-01",
            ]);

            if (!empty($request->logo)) {
                do {
                    $val = substr(str_shuffle(str_repeat("0123456789abcdefghijklmnopqrstuvwxyz", 5)), 0, 5);
                    $val = "{$val}.{$request->file('logo')->extension()}";
                } while (!empty(Experience::where('logo_company', $val)->first()));
    
                Storage::disk('public')->putFileAs(
                    "experience",
                    $request->file('logo'),
                    $val
                );

                $updated['logo_company'] = $val;
            }

            $experience->update($updated);

            $this->response_body['status'] = True;
            $this->response_body['message'] = "Experience is updated";
            $this->response_body['data'] = route('backoffice.experience.index');
        } catch (\Throwable $t) {
            $this->response_body['status'] = False;
            $this->response_body['message'] = $t->getMessage();
            $status = 500;
        }

        return $this->_generate_response($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Experience  $experience
     * @return \Illuminate\Http\Response
     */
    public function destroy(Experience $experience)
    {
        //
    }
}

resources/views/backoffice/base.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>@yield('title')</title>
    <!-- General CSS Files -->
    <link rel='shortcut icon' type='image/x-icon' href="{{ asset('backoffice/assets/img/favicon.ico') }}" />

    <link rel="stylesheet" href="{{ asset('backoffice/assets/css/app.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/bootstrap-social/bootstrap-social.css') }}">
    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('backoffice/assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/css/components.css') }}">
    <!-- Custom style CSS -->
    <link rel="stylesheet" href="{{ asset('backoffice/assets/css/custom.css') }}">

    <!-- third party CSS -->
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/izitoast/css/iziToast.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/datatables/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/bootstrap-daterangepicker/daterangepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/jquery-selectric/selectric.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/bootstrap-timepicker/css/bootstrap-timepicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backoffice/assets/bundles/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">

    @yield('custom_css')
</head>

<body>
    <div class="loader"></div>
    <div id="app">
        <section class="section">
            @yield('content')
        </section>
    </div>
    <!-- General JS Scripts -->
    <script src="{{ asset('backoffice/assets/js/app.min.js') }}"></script>
    <!-- JS Libraies -->
    <!-- Page Specific JS File -->
    <!-- Template JS File -->
    <script src="{{ asset('backoffice/assets/js/scripts.js') }}"></script>
    <!-- Custom JS File -->
    <script src="{{ asset('backoffice/assets/js/custom.js') }}"></script>

    <!-- third party JS -->
    <script src="{{ asset('backoffice/assets/bundles/izitoast/js/iziToast.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/prism/prism.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/cleave-js/dist/cleave.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/cleave-js/dist/addons/cleave-phone.us.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/jquery-pwstrength/jquery.pwstrength.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/jquery-selectric/jquery.selectric.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/js/page/forms-advanced-forms.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('backoffice/assets/bundles/jquery-steps/jquery.steps.min.js') }}"></script>
    <script src="https://cdn.ckeditor.com/4.19.1/standard/ckeditor.js"></script>
    <script src="{{ asset('backoffice/assets/bundles/sweetalert/sweetalert.min.js') }}"></script>
    <!-- Page Specific JS File -->
    <script src="{{ asset('backoffice/assets/js/page/sweetalert.js') }}"></script>
    <script>
        let form, url, method;

        // defined default value for ajax settings for accomodate formdata or general utf-8 format
        let contentType = "application/x-www-form-urlencoded; charset=UTF-8"
        let processData = true

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>

    @yield('modal')
    @yield('custom_js')
    <script>
        $(form).submit(function(event) {
            event.preventDefault();

            $.ajax({
                url: url,
                method: method,
                dataType : 'json',
                cache : false,
                contentType : contentType,
                processData : processData,
                data: generate_payload(),
                success: function(data) {
                    event.preventDefault();
                    iziToast.success({
                        title: data.message,
                        message: "",
                        position: 'topRight'
                    });

                    success_callback(data);
                },
                error: function(xhr) {
                    if (typeof xhr.responseJSON.message === "string") {
                        message = xhr.responseJSON.message
                    } else {
                        message = xhr.responseJSON.message.join()
                    }

                    event.preventDefault();
                    iziToast.error({
                        title: xhr.statusText,
                        message: message,
                        position: 'topRight'
                    });

                    fail_callback(xhr);
                }
            })
        })
    </script>
    <!-- Extra JS if in modal -->
</body>


<!-- Mirrored from radixtouch.in/templates/admin/aegis/source/light/auth-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 12 Sep 2019 06:54:04 GMT -->

</html>

resources/views/backoffice/template.blade.php
@extends('backoffice.base')

@section('custom_css')
    @yield('page_css')
@endsection

@section('content')
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg main-navbar">
            <div class="form-inline mr-auto">
                <ul class="navbar-nav mr-3">
                    <li><a href="#" data-toggle="sidebar"
                            class="nav-link nav-link-lg
                                    collapse-btn"> <i
                                data-feather="align-justify"></i></a></li>
                    <li><a href="#" class="nav-link nav-link-lg fullscreen-btn">
                            <i data-feather="maximize"></i>
                        </a></li>
                    <li>
                        <form class="form-inline mr-auto">
                            <div class="search-element">
                                <input class="form-control" type="search" placeholder="Search" aria-label="Search"
                                    data-width="200">
                                <button class="btn" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav navbar-right">
                <!-- Message and notification list -->
                <!-- end here -->>

                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user"> <img
                            alt="image" src="{{ asset('backoffice/assets/img/user.png') }}"
                            class="user-img-radious-style"> <span class="d-sm-none d-lg-inline-block"></span></a>
                    <div class="dropdown-menu dropdown-menu-right pullDown">
                        <div class="dropdown-title">Halo, Admin</div>
                        <a href="" class="dropdown-item has-icon">
                            <i class="far fa-user"></i> Profile
                        </a>
                        <a href="timeline.html" class="dropdown-item has-icon">
                            <i class="fas fa-bolt"></i>
                            Activities
                        </a>
                        <a href="#" class="dropdown-item has-icon"> <i class="fas fa-cog"></i>
                            Settings
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger"> <i
                                class="fas fa-sign-out-alt"></i>
                            Logout
                        </a>
                    </div>
                </li>
            </ul>
        </nav>

        <!-- sidebar -->
        <div class="main-sidebar sidebar-style-2">
            <aside id="sidebar-wrapper ">
                <div class="sidebar-brand mb-5 py-3">
                    <a href="{{ route('backoffice.index') }}">
                        <img src="{{asset('backoffice/assets/img/logo.png')}}" class="header-logo">
                        <span class="logo-name">Portfolio</span>
                    </a>
                </div>

                <div class="sidebar-user">
                    <div class="sidebar-user-picture">
                        <img alt="image" src="{{ asset('backoffice/assets/img/userbig.png') }}">
                    </div>
                    <div class="sidebar-user-details">
                        <div class="user-name">Admin</div>
                        <div class="user-role">
                            ADMIN
                        </div>
                    </div>
                </div>
                <ul class="sidebar-menu">
                    <li class="menu-header">Utama</li>
                    <li class="@yield('home__active')">
                        <a href="{{ route('backoffice.index') }}" class="nav-link">
                            <i class="fas fa-briefcase"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>

                    <li class="@yield('information__active')">
                        <a href="{{ route('backoffice.information.index') }}" class="nav-link">
                            <i class="fas fa-book"></i>
                            <span>Infomasi</span>
                        </a>
                    </li>

                    <li class="@yield('education__active')">
                        <a href="{{ route('backoffice.education.index') }}" class="nav-link">
                            <i class="fas fa-user-graduate"></i>
                            <span>Pendidikan</span>
                        </a>
                    </li>

                    <li class="@yield('skill__active')">
                        <a href="{{ route('backoffice.skill.index') }}" class="nav-link">
                            <i class="fas fa-ruler-horizontal"></i>
                            <span>Skill</span>
                        </a>
                    </li>

                    <li class="@yield('project__active')">
                        <a href="{{ route('backoffice.project.index') }}" class="nav-link">
                            <i class="fas fa-suitcase"></i>
                            <span>Project</span>
                        </a>
                    </li>

                    <li class="@yield('experience__active')">
                        <a href="{{ route('backoffice.experience.index') }}" class="nav-link">
                            <i class="fas fa-chalkboard"></i>
                            <span>Pengalaman</span>
                        </a>
                    </li>
                </ul>
            </aside>
        </div>

        <!-- main content -->
        <div class="main-content">
            <section class="section">
                <div class="section-body">
                    <div id="loadericon"></div>
                    @yield('main-content')
                </div>
            </section>
        </div>

        <footer class="main-footer">
            <div class="footer-left">
                Copyright &copy; 2019 <div class="bullet"></div> Design and developed By <a target="_blank"
                    href="https://rezawramadhan.xyz/">BigR</a>
            </div>
            <div class="footer-right">
            </div>
        </footer>
    </div>
@endsection

@section('custom_js')
    @yield('page_js')

    <script>
        function ajax_delete(url) {
            $.ajax({
                url: url,
                method:"DELETE",
                success: function(data) {
                    event.preventDefault();
                    iziToast.success({
                        title: data.message,
                        message: "",
                        position: 'topRight'
                    });

                    success_callback(data);
                },
                error: function(xhr) {
                    if (typeof xhr.responseJSON.message === "string") {
                        message = xhr.responseJSON.message
                    } else {
                        message = xhr.responseJSON.message.join()
                    }

                    event.preventDefault();
                    iziToast.error({
                        title: xhr.statusText,
                        message: message,
                        position: 'topRight'
                    });

                    fail_callback(xhr);
                }
            })
        }
    </script>
@endsection